version: "3.7"
services:
  db:
    container_name: mariadb
    image: mariadb
    environment:
      MARIADB_DATABASE: test
      MARIADB_ROOT_PASSWORD: mariadb
    ports:
      - "3306:3306"
    restart: always